# Generated by Django 3.2 on 2021-09-13 14:34

import cuser.fields
from datetime import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_data(apps, schema_editor):

    Formulario = apps.get_model("nucleo", "Formulario")
    Pergunta = apps.get_model("nucleo", "Pergunta")
    User = apps.get_model("auth", "User")

    agora = datetime.now()
    usuario = User.objects.filter(is_superuser=True, is_active=True, is_staff=True).order_by('date_joined').first()

    Formulario.objects.filter(
        ativo=False,
        desativado_em__isnull=True
    ).update(
        desativado_por=usuario,
        desativado_em=agora
    )

    Pergunta.objects.filter(
        ativo=False,
        desativado_em__isnull=True
    ).update(
        desativado_por=usuario,
        desativado_em=agora
    )

def reverse_migrate_data(apps, schema_editor):

    Formulario = apps.get_model("nucleo", "Formulario")
    Pergunta = apps.get_model("nucleo", "Pergunta")

    Formulario.objects.filter(
        desativado_em__isnull=False
    ).update(
        ativo=False
    )

    Pergunta.objects.filter(
        desativado_em__isnull=False
    ).update(
        ativo=False
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0014_add_apoio_pode_registrar_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cadastrado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_formulario_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulario',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_formulario_desativado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_formulario_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='cadastrado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_pergunta_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_pergunta_desativado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_pergunta_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='cadastrado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_resposta_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resposta',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_resposta_desativado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resposta',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='modificado_por',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nucleo_resposta_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'Texto'), (1, 'Número'), (2, 'Data'), (3, 'Lista'), (4, 'Sessão')], default=0),
        ),
        migrations.RunPython(
            code=migrate_data,
            reverse_code=reverse_migrate_data,
            atomic=True
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='classe_css',
            field=models.CharField(blank=True, default='', help_text='Classe CSS (Ex: span6)', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['formulario', 'sessao__posicao', 'posicao'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AddField(
            model_name='resposta',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.evento'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='atendimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atendimento.atendimento'),
        ),
    ]
