# Generated by Django 3.2 on 2022-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_auditoria_pergunta_tipo_sessao_classe_css_resposta_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='lista_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='texto_complementar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'Texto (Curto)'), (6, 'Texto (Longo)'), (1, 'Número'), (2, 'Data'), (3, 'Lista (Única)'), (5, 'Lista (Múltipla)'), (4, 'Sessão')], default=0),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='classe_css',
            field=models.CharField(blank=True, default='', help_text='Classe CSS (Ex: input-xxlarge)', max_length=255),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
