# Generated by Django 3.2 on 2022-04-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modelodocumento_formulario'),
        ('nucleo', '0016_pergunta_lista_url_texto_complementar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='respostas', to='core.evento'),
        ),
    ]
