# Generated by Django 3.2 on 2022-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0017_alter_resposta_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='exibir_em_atendimento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='exibir_em_atividade_extraordinaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='gerar_alerta_em_atendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
    ]
