# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0048_create_all_views_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonial',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assistido.pessoa'),
        ),
        migrations.AlterField(
            model_name='perfilcamposobrigatorios',
            name='parte_principal',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Parte Principal?'),
        ),
        migrations.AlterField(
            model_name='pessoaassistida',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistido.pessoa'),
        ),
    ]
