# Generated by Django 3.2 on 2021-06-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0049_django_32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonial',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='assistido.pessoa'),
        ),
    ]
