# Generated by Django 3.2 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0050_alter_patrimonial_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='situacao',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Criança ou adolescente'), (1, 'Portador de Necessidades Especiais'), (2, 'Idoso'), (3, 'Egresso do sistema prisional')], null=True, verbose_name='Situação'),
        ),
    ]
