# Generated by Django 3.2 on 2022-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0051_dependente_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cadastro_protegido',
            field=models.BooleanField(default=False, verbose_name='Cadastro protegido contra alterações (cpf/cnpj, nome/razão social, apelido/nome fantasia)'),
        ),
    ]
