# Generated by Django 3.2 on 2022-06-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0053_add_acesso_permissao_violencia_domestica'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='situacao_dependente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='situacao', to='assistido.situacao'),
        ),
        migrations.AddField(
            model_name='situacao',
            name='eh_situacao_deducao',
            field=models.BooleanField(default=False, verbose_name='É uma situação onde que há dedução no cálculo de hipossuficiência?'),
        ),
    ]
