# Generated by Django 3.2 on 2022-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0055_add_tipo_renda'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='disponivel_via_app',
            field=models.BooleanField(default=False, verbose_name='Disponível via apps (Luna, eDefensor, etc)?'),
        ),
    ]
