# Generated by Django 3.2 on 2022-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0056_situacao_disponivel_via_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonial',
            name='eh_bem_familia',
            field=models.BooleanField(default=False, verbose_name='É bem de família destinado a residência?'),
        ),
    ]
