# Generated by Django 3.2 on 2022-08-26 09:39

import assistido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0057_patrimonial_eh_bem_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=assistido.models.documento_file_name, validators=[assistido.models.validate_file_size_extension], verbose_name='Arquivo'),
        ),
    ]
