# Generated by Django 3.2 on 2023-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0058_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patrimonial',
            index=models.Index(condition=models.Q(desativado_em=None), fields=['pessoa', 'tipo'], name='assistido_patrimonial_idx_001'),
        ),
    ]
