# Generated by Django 3.2 on 2023-05-22 16:19

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion

LISTA_SEXO = (
    (0, 'Masculino'),
    (1, 'Feminino'),
    (2, 'Não Binário')
)


def carregar_dados(apps, schema_editor):
    Pessoa = apps.get_model('assistido', 'Pessoa')
    Pessoa.objects.filter(
        sexo__in=[0,1,2]
    ).update(
        genero=F('sexo')
    )

def reverse_carregar_dados(apps, schema_editor):
    Pessoa = apps.get_model('assistido', 'Pessoa')
    Pessoa.objects.filter(
        genero__in=[0,1,2]
    ).update(
        sexo=F('genero')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0080_generopessoa'),
        ('assistido', '0060_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.generopessoa', verbose_name='Gênero'),
        ),
        migrations.RunPython(
            code=carregar_dados,
            reverse_code=reverse_carregar_dados,
        )
    ]
