# Generated by Django 3.2 on 2023-06-06 20:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistido', '0061_pessoa_genero_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_dependente_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_dependente_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentoassinado',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_documentoassinado_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentoassinado',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_documentoassinado_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patrimonial',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_patrimonial_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patrimonial',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_patrimonial_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patrimonialtipo',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_patrimonialtipo_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patrimonialtipo',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_patrimonialtipo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_pessoa_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_pessoa_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_situacao_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_situacao_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiporenda',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistido_tiporenda_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiporenda',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='assistido_tiporenda_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
