# Generated by Django 3.2 on 2021-05-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0045_distribuicao_por_polo_e_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='fase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo.fase'),
        ),
        migrations.AlterField(
            model_name='processoassunto',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.assunto'),
        ),
        migrations.AlterField(
            model_name='processoassunto',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processo'),
        ),
    ]
