# Generated by Django 3.2 on 2021-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0046_django_32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
