# Generated by Django 3.2 on 2021-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0047_alter_fase_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestacao',
            name='mensagem_resposta',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
