# Generated by Django 3.2 on 2021-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0048_alter_manifestacao_mensagem_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridade',
            name='codigo_mni',
            field=models.CharField(max_length=256),
        ),
    ]
