# Generated by Django 3.2 on 2022-03-10 16:02

from django.db import migrations, models

def migrate_data(apps, schema_editor):

    Audiencia = apps.get_model("processo", "Audiencia")
    AUDIENCIA_REALIZADA = 1

    Audiencia.objects.filter(
        audiencia_realizada=True
    ).update(
        audiencia_status=AUDIENCIA_REALIZADA
    )

def reverse_migrate_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0050_modificado_em_processo_parte_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='audiencia_status',
            field=models.SmallIntegerField(choices=[(0, 'Audiência marcada'), (1, 'Audiência realizada'), (2, 'Audiência cancelada')], default=0),
        ),
        migrations.RunPython(
            code=migrate_data,
            reverse_code=reverse_migrate_data,
            atomic=True
        ),
    ]
