# Generated by Django 3.2 on 2022-05-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cuser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0112_qualificacao_peso_e_exibir_em_atendimentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo', '0051_audiencia_audiencia_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_manifestacaoparte_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_manifestacaoparte_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partes', to='processo.manifestacao')),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_manifestacaoparte_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atendimento.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
