# Generated by Django 3.2 on 2023-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0053_prioridade_disponivel_para_peticionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='credencial_mni_cadastro',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Credencial MNI de Cadastro'),
        ),
    ]
