# Generated by Django 3.2 on 2023-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0055_partehistoricosituacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='situacao_atual',
            field=models.IntegerField(choices=[(10, 'Em andamento'), (20, 'Sobrestado'), (30, 'Finalizado')], default=10),
        ),
    ]
