# Generated by Django 3.2 on 2023-02-10 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cuser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0023_atuacao_foi_enviado_email_plantao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0076_alter_etiqueta_nome'),
        ('processo', '0056_add_parte_situacao_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('foi_redistribuido', models.BooleanField(default=False, verbose_name='Foi Redistribuido?')),
                ('numero_aviso', models.CharField(blank=True, default=None, help_text='Número do Aviso no Tribunal de Justiça', max_length=100, null=True)),
                ('numero_processo', models.CharField(blank=True, default=None, help_text='Número do Processo Judicial', max_length=100, null=True)),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_distribuicao_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_distribuicao_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('distribuido_defensor', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='defensor.defensor')),
                ('distribuido_defensoria', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contrib.defensoria')),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_distribuicao_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processo.processo')),
            ],
            options={
                'verbose_name': 'Registro de Distribuição',
                'verbose_name_plural': 'Registros de Distribuições',
            },
        ),
        migrations.CreateModel(
            name='Redistribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('foi_redistribuido', models.BooleanField(default=False, verbose_name='Foi Redistribuido?')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_redistribuicao_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_redistribuicao_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('distribuicao_origem', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processo.distribuicao')),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_redistribuicao_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('redistribuido_defensor', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='defensor.defensor')),
                ('redistribuido_defensoria', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contrib.defensoria')),
            ],
            options={
                'verbose_name': 'Registro de Redistribuição',
                'verbose_name_plural': 'Registros de Redistribuições',
            },
        ),
    ]
