# Generated by Django 3.2 on 2023-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0058_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='evento_eproc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
