# Generated by Django 3.2 on 2023-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0059_alter_fase_evento_eproc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='audiencia_status',
            field=models.SmallIntegerField(choices=[(0, 'Audiência marcada'), (1, 'Audiência realizada'), (2, 'Audiência cancelada'), (3, 'Audiência não realizada/Advogado constituído')], default=0),
        ),
    ]
