# Generated by Django 3.2 on 2023-04-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0131_indices'),
        ('processo', '0060_alter_audiencia_audiencia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofase',
            name='documento_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.documento', verbose_name='Documento'),
        ),
    ]
