# Generated by Django 3.2 on 2023-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0062_django_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetipo',
            name='habeas_corpus',
            field=models.BooleanField(default=False, verbose_name='Habeas Corpus'),
        ),
        migrations.AddField(
            model_name='fasetipo',
            name='peticao_inicial',
            field=models.BooleanField(default=False, verbose_name='Petição Inicial'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='atividade',
            field=models.SmallIntegerField(choices=[(0, 'Outra'), (1, 'Audiência'), (2, 'Júri'), (3, 'Sentença'), (4, 'Recurso'), (5, 'Petição Inicial'), (6, 'Habeas Corpus')], default=0),
        ),
    ]
