version: '3'

services:
  redis:
    image: redis
    volumes:
     - ./data/redis/:/data/
    restart: always
  memcached:
    image: memcached
    restart: always
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/python:latest
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    depends_on:
      - redis
      - memcached
      - python
    env_file:
      - .env
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    volumes:
     - ./media/:/app/src/media/
     - ./data/wkhtmltox/:/app/src/binarios_executaveis/
    restart: always
  worker_geral:
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    command: ["celery", "--app=taskapp", "worker", "--queues=default,geral", "--concurrency=4", "-n worker-geral@%h"]
    depends_on:
      - redis
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    volumes:
      - ./media/:/app/src/media/
      - ./data/wkhtmltox/:/app/src/binarios_executaveis/
    restart: always
  worker_sobdemanda:
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    command: ["celery", "--app=taskapp", "worker", "--queues=sobdemanda", "--concurrency=4", "-n worker-sobdemanda@%h"]
    depends_on:
      - redis
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    volumes:
      - ./media/:/app/src/media/
      - ./data/wkhtmltox/:/app/src/binarios_executaveis/
    restart: always
  worker_prioridade:
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    command: ["celery", "--app=taskapp", "worker", "--queues=prioridade", "--concurrency=4", "-n worker-prioridade@%h"]
    depends_on:
      - redis
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    volumes:
      - ./media/:/app/src/media/
      - ./data/wkhtmltox/:/app/src/binarios_executaveis/
    restart: always
  worker_manifestacao:
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    command: ["celery", "--app=taskapp", "worker", "--queues=manifestacao", "--concurrency=4", "-n worker-manifestacao@%h"]
    depends_on:
      - redis
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    volumes:
      - ./media/:/app/src/media/
      - ./data/wkhtmltox/:/app/src/binarios_executaveis/
    restart: always
  beat:
    env_file:
      - .env
    command: ["celery", "--app=taskapp", "beat", "--loglevel", "INFO", "--scheduler=django_celery_beat.schedulers:DatabaseScheduler"]
    depends_on:
      - worker_geral
      - worker_sobdemanda
      - worker_prioridade
    image: gitlab.defensoria.to.def.br:5000/defensoria/sisat/web:latest
    restart: always
  flower:
    env_file:
      - .env
    command: ["flower", "--broker=redis://redis:6379/2", "--port=5555", "--purge_offline_workers=10"]
    depends_on:
      - worker_geral
      - worker_sobdemanda
      - worker_prioridade
    image: mher/flower:0.9.7
    ports:
      - 5555:5555
    restart: always
