# Generated by Django 3.2 on 2022-03-04 15:20

from django.db import migrations, models
import jsonfield.fields
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_files = [
        'relatorios/fixtures/relatorio.json',
        'relatorios/fixtures/local.json'
    ]

    print("")
    for fixture_file in fixture_files:
        with open(fixture_file, 'rb') as fixture:
            print("Importando dados do arquivo '{}'".format(fixture_file))
            objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
            for obj in objects:
                obj.save()


def unload_fixture(apps, schema_editor):
    pass


def migrate_data(apps, schema_editor):
    from django.contrib.auth.models import Permission
    from contrib.models import Papel

    Local = apps.get_model("relatorios", "Local")

    Local.objects.create(
        pagina='relatorio_listar',
        posicao=0,
        titulo='Metabase',
        classe_css='fas fa-chart-pie text-success',
    )

    # Vincula os relatórios que tinham permissões aos papéis que possuíam a permissão correspondente
    permissoes = {
        'view_relat_atividades': [1, 2],  # permission_codename: [relatorio_id]
        'view_relat_atividades_mensal': [3, 4, 5, 6, 7, 8, 24],
        'view_relat_atividades_indenizatorias': [25],
        'view_relat_atuacoes_servidores_por_periodo': [26],
        'view_relat_atividades_servidores': [10],
        'view_relat_atendimentos_defensor': [15, 17, 42, 43, 59],
        'view_relat_atendimentos_substitutos': [44],
        'view_relat_atendimentos_acordo': [11],
        'view_relat_atendimentos_primeiro_do_dia': [12],
        'view_relat_multidisciplinar': [41, 60],
        'view_relat_diligencia': [9, 61],
        'view_relat_plantao_periodo': [39],
        'view_relat_plantao_periodo_defensor': [40],
        'view_relat_processos': [21, 22, 23],
        'view_relat_processo_fase_acumulacao': [28],
        'view_relat_processo_fase_substituicao': [29],
        'view_relat_perfil_assistidos': [18, 20],
        'view_relat_perfil_assistidos_atendimento': [19],
        'view_relat_penal_visita': [30, 31, 32, 37, 38],
        'view_relat_penal_atendimento_interessados': [33, 34],
        'view_relat_penal_presos_provisorios': [35],
        'view_relat_penal_presos_condenados': [36],
        'view_relat_processos_pendentes_por_defensor': [27],
        'view_relat_tempo_espera_atendimento_defensor': [13, 14],
        'view_relat_atendimentos_por_qualificacao_total': [16],
        'view_relat_indeferimentos': [45, 46],
    }

    print("")

    for codename in permissoes:

        print("Incluindo relatórios aos papéis vinculados à permissão: {}".format(codename))

        perm = Permission.objects.filter(codename=codename).first()
        relatorios = permissoes[codename]

        if perm:
            for grupo in perm.group_set.all():
                for papel in grupo.papel_set.all():
                    papel.relatorios.add(*relatorios)

    # Vincula os relatórios que não tinham permissão a todos os papéis
    relatorios = [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58]

    for papel in Papel.objects.all():
        print("Incluindo relatórios sem permissão ao papel: {}".format(papel))
        papel.relatorios.add(*relatorios)


def reverse_migrate_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0031_perm_view_filter_servidores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={
                'ordering': ['pagina', 'posicao', 'titulo'],
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais'},
        ),
        migrations.AddField(
            model_name='local',
            name='classe_css',
            field=models.CharField(
                blank=True,
                default='fas fa-file-pdf text-error',
                help_text='Classe CSS (Ex: fas fa-chart-pie text-success)',
                max_length=255),
        ),
        migrations.AddField(
            model_name='local',
            name='posicao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='metabase_dashboard_id',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='ID do Dashboard (Painel) do Metabase'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jasper'), (2, 'Metabase')], default=1),
        ),
        migrations.AlterField(
            model_name='local',
            name='parametros',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.RunPython(
            code=load_fixture,
            reverse_code=unload_fixture,
            atomic=True
        ),
        migrations.RunPython(
            code=migrate_data,
            reverse_code=reverse_migrate_data,
            atomic=True
        ),
    ]
