# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classe_indeferimento_pode_registrar_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Pedido'), (6030, 'Impedimento'), (6040, 'Suspeição'), (6050, 'Negação'), (6051, 'Negação por Hipossuficiência'), (6052, 'Denegação de Procedimento')], default=10),
        ),
    ]
