# Generated by Django 3.2 on 2021-09-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djdocuments', '0018_django_32'),
        ('nucleo', '0015_auditoria_pergunta_tipo_sessao_classe_css_resposta_evento'),
        ('core', '0012_django_32'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodocumento',
            name='formulario_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_modelos_documentos', to='nucleo.formulario', verbose_name='Modelo Formulário'),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='ged_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_modelos_documentos', to='djdocuments.documento', verbose_name='Modelo GED'),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'GED'), (1, 'Jasper'), (2, 'Formulário')], default=0),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='core.tipodocumento'),
        ),
    ]
