# Generated by Django 3.2 on 2023-02-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0076_alter_etiqueta_nome'),
        ('core', '0013_modelodocumento_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.area'),
        ),
    ]
