# Generated by Django 3.2 on 2023-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_evento_area'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(condition=models.Q(desativado_em=None), fields=['processo', 'setor_criacao'], name='core_evento_idx_001'),
        ),
    ]
