# Generated by Django 3.2 on 2022-07-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0117_tarefa_movimento'),
        ('honorarios', '0012_auto_20180123_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='atendimento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='honorarios', to='atendimento.defensor'),
        ),
    ]
