# Generated by Django 3.2 on 2023-06-06 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('honorarios', '0014_honorario_modificado_por_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='honorarios_honorario_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
