# Generated by Django 3.2 on 2023-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0014_evento_evento_evento_idx_001'),
        ('processo', '0061_documentofase_documento_atendimento'),
        ('core', '0016_documento_nivel_sigilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorMeritocracia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('audiencia_com_acordo', models.BooleanField(default=False)),
                ('audiencia_sem_acordo', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('tipos_agendas', models.ManyToManyField(blank=True, to='evento.Categoria')),
                ('tipos_atividades', models.ManyToManyField(blank=True, to='core.TipoEvento')),
                ('tipos_documentos', models.ManyToManyField(blank=True, to='djdocuments.TipoDocumento')),
                ('tipos_fases_processuais', models.ManyToManyField(blank=True, to='processo.FaseTipo')),
            ],
            options={
                'verbose_name': 'Indicador de Meritocracia',
                'verbose_name_plural': 'Indicadores de Meritocracia',
                'ordering': ['-ativo', 'nome'],
            },
        ),
    ]
