# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0102_atendimento_tipo_motivo_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensor',
            name='atendimento_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atendimento.atendimento'),
        ),
    ]
