# Generated by Django 3.2 on 2021-07-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0103_django_32'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atendimento.qualificacao'),
        ),
    ]
