# Generated by Django 3.2 on 2021-08-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0104_tarefa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atendimento.qualificacao'),
        ),
    ]
