# Generated by Django 3.2 on 2021-09-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0057_defensoria_dpe_am'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0105_alter_tarefa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoAssistido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data e hora informação')),
                ('assistido', models.CharField(max_length=200)),
                ('atendente', models.CharField(max_length=200)),
                ('informacao', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Informação',
                'verbose_name_plural': 'Informações',
                'permissions': (('view_informacao', 'Can view Informação'),),
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='detalhes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Detalhes do Ofício'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='oficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='atendente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='attprocedimento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atendimento.atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ligação'), (1, 'Inicial'), (2, 'Retorno'), (3, 'Recepção'), (1031, 'Solicitação de Apoio de Núcleo Especializado'), (4, 'Apoio de Núcleo Especializado'), (5, 'Anotação'), (6, 'Processo'), (7, 'Visita ao Preso'), (8, 'Atendimento ao Interessado'), (9, 'Encaminhamento'), (10, 'Atividade'), (1092, 'Notificação'), (11, 'Reclamacao pelo disk'), (12, 'Informacao pelo disk'), (13, 'Ofício encaminhado'), (14, 'Ofício finalizado')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Agendamento Inicial'), (2, 'Agendamento Retorno'), (3, 'Encaminhamento'), (4, 'Informação'), (5, 'Reagendamento'), (6, 'Informação ao Assistido'), (7, 'Reclamação')]),
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data e hora reclamacao')),
                ('assistido', models.CharField(max_length=200)),
                ('atendente', models.CharField(max_length=200)),
                ('reclamacao', models.CharField(max_length=1000)),
                ('nome_estabelecimento', models.CharField(max_length=255, null=True)),
                ('tipo_estabelecimento', models.SmallIntegerField(choices=[(1, 'Comercial'), (2, 'Industrial'), (3, 'Residencial')], null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco_estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.endereco')),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
            },
        ),
    ]
