# Generated by Django 3.2 on 2021-10-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0108_vw_atendimento_defensor_forma_atendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-ativo', '-numero'], 'permissions': (('delete_anotacao', 'Pode excluir anotação'), ('agendar_com_bloqueio', 'Pode agendar em dia com bloqueio (feriado)'), ('change_all_agendamentos', 'Pode alterar agendamentos de qualquer comarca'), ('view_all_atendimentos', 'Pode ver teor de atendimentos públicos e privados'), ('view_129', 'Pode ver Painel 129'), ('view_recepcao', 'Pode ver Painel da Recepção'), ('view_defensor', 'Pode ver Painel do Defensor'), ('view_distribuicao', 'Pode ver Painel de Distribuição de Atendimentos'), ('view_painel', 'Pode ver Painel de Senhas'), ('unificar_atendimento', 'Pode unificar atendimentos'), ('requalificar_atendimento_retroativo', 'Pode requalificar atendimento retroativo'), ('encaminhar_atendimento_para_qualquer_area', 'Pode encaminhar atendimento p/ qualquer área'), ('atender_retroativo', 'Pode atender retroativo')), 'verbose_name': 'Atendimento Geral', 'verbose_name_plural': 'Atendimentos Gerais'},
        ),
    ]
