# Generated by Django 3.2 on 2021-09-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0109_alter_atendimento_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
