# Generated by Django 3.2 on 2022-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0111_tarefa_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificacao',
            name='exibir_em_atendimentos',
            field=models.BooleanField(default=True, verbose_name='Indica se deve ser exibido ao usuário final na tela de seleção de qualificações de atendimento'),
        ),
        migrations.AddField(
            model_name='qualificacao',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Campo opcional para ser utilizado em relatórios que computam peso na qualificação de atendimento', max_digits=16, null=True),
        ),
    ]
