# Generated by Django 3.2 on 2022-04-12 12:04

from django.db import migrations

def migrate_data(apps, schema_editor):
    Arvore = apps.get_model("atendimento", "Arvore")
    total = Arvore.objects.filter(ativo=True).update(ativo=False)
    print('\n{} arvores invalidadas!'.format(total))

class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0112_qualificacao_peso_e_exibir_em_atendimentos'),
    ]

    operations = [
         migrations.RunPython(
            code=migrate_data,
            reverse_code=migrate_data,
            atomic=True
        ),
    ]
