# Generated by Django 3.2 on 2022-06-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0113_avore_invalidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificacao',
            name='orgao_encaminhamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atendimento.encaminhamento'),
        ),
    ]
