# Generated by Django 3.2 on 2022-09-02 19:13

import atendimento.atendimento.models
import contrib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0118_qualificacao_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=atendimento.atendimento.models.documento_file_name, validators=[contrib.validators.validate_file_size_extension], verbose_name='Anexo'),
        ),
    ]
