# Generated by Django 3.2 on 2022-10-21 14:59

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0121_grupodedefensoriasparaagendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVulnerabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de atendimento')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição da vulnerabilidade')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_tipovulnerabilidade_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_tipovulnerabilidade_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_tipovulnerabilidade_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Vulnerabilidade Digital',
                'verbose_name_plural': 'Tipos de Vulnerabilidades Digitais',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoVulnerabilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atendimento.atendimento', verbose_name='Atendimento')),
                ('vulnerabilidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atendimento.tipovulnerabilidade')),
            ],
            options={
                'verbose_name': 'Atendimento/Vulnerabilidade',
                'verbose_name_plural': 'Atendimentos/Vulnerabilidades',
                'db_table': 'atendimento_atendimento_vulnerabilidade',
            },
        ),
    ]
