# Generated by Django 3.2 on 2022-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0122_atendimentovulnerabilidade_tipovulnerabilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-ativo', '-numero'], 'permissions': (('delete_anotacao', 'Pode excluir anotação'), ('agendar_com_bloqueio', 'Pode agendar em dia com bloqueio (feriado)'), ('change_all_agendamentos', 'Pode alterar agendamentos de qualquer comarca'), ('view_all_atendimentos', 'Pode ver teor de atendimentos públicos e privados'), ('view_129', 'Pode ver Painel 129'), ('view_recepcao', 'Pode ver Painel da Recepção'), ('view_defensor', 'Pode ver Painel do Defensor'), ('view_distribuicao', 'Pode ver Painel de Distribuição de Atendimentos'), ('view_painel', 'Pode ver Painel de Senhas'), ('unificar_atendimento', 'Pode unificar atendimentos'), ('requalificar_atendimento_retroativo', 'Pode requalificar atendimento retroativo'), ('encaminhar_atendimento_para_qualquer_area', 'Pode encaminhar atendimento p/ qualquer área'), ('atender_retroativo', 'Pode atender retroativo'), ('remeter_atendimento', 'Pode remeter atendimento para outra Defensoria'), ('arquivar_atendimento', 'Pode arquivar um atendimento'), ('desarquivar_atendimento', 'Pode desarquivar um atendimento'), ('view_encaminhar_oficio', 'Can view botão encaminhar oficio')), 'verbose_name': 'Atendimento Geral', 'verbose_name_plural': 'Atendimentos Gerais'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ligação'), (1, 'Inicial'), (2, 'Retorno'), (3, 'Recepção'), (1031, 'Solicitação de Apoio de Núcleo Especializado'), (4, 'Apoio de Núcleo Especializado'), (5, 'Anotação'), (6, 'Processo'), (7, 'Visita ao Preso'), (8, 'Atendimento ao Interessado'), (9, 'Encaminhamento'), (10, 'Atividade'), (1092, 'Notificação'), (11, 'Reclamacao pelo disk'), (12, 'Informacao pelo disk'), (13, 'Ofício encaminhado'), (14, 'Ofício finalizado'), (999, 'Atendimento arquivado'), (998, 'Atendimento desarquivado')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='qualificacao',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Pedido'), (20, 'Atividade'), (30, 'Anotação'), (31, 'Notificação (chatbot)'), (40, 'Tarefa'), (50, 'Remetimento atendimento'), (60, 'Arquivamento com resolução'), (61, 'Arquivamento sem resolução'), (62, 'Desarquivamento')], default=10),
        ),
    ]
