# Generated by Django 3.2 on 2022-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0074_etiqueta'),
        ('atendimento', '0124_pasta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificacao',
            name='defensorias',
            field=models.ManyToManyField(blank=True, related_name='qualificacoes', to='contrib.Defensoria'),
        ),
    ]
