# Generated by Django 3.2 on 2023-01-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0125_qualificacao_defensorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-ativo', '-numero'], 'permissions': (('delete_anotacao', 'Pode excluir anotação'), ('agendar_com_bloqueio', 'Pode agendar em dia com bloqueio (feriado)'), ('change_all_agendamentos', 'Pode alterar agendamentos de qualquer comarca'), ('view_all_atendimentos', 'Pode ver teor de atendimentos públicos e privados'), ('view_129', 'Pode ver Painel 129'), ('view_recepcao', 'Pode ver Painel da Recepção'), ('view_defensor', 'Pode ver Painel do Defensor'), ('view_distribuicao', 'Pode ver Painel de Distribuição de Atendimentos'), ('view_painel', 'Pode ver Painel de Senhas'), ('unificar_atendimento', 'Pode unificar atendimentos'), ('requalificar_atendimento_retroativo', 'Pode requalificar atendimento retroativo'), ('encaminhar_atendimento_para_qualquer_area', 'Pode encaminhar atendimento p/ qualquer área'), ('atender_retroativo', 'Pode atender retroativo'), ('atender_sem_liberar', 'Pode atender sem liberar na recepção'), ('remeter_atendimento', 'Pode remeter atendimento para outra Defensoria'), ('arquivar_atendimento', 'Pode arquivar um atendimento'), ('desarquivar_atendimento', 'Pode desarquivar um atendimento'), ('view_encaminhar_oficio', 'Can view botão encaminhar oficio')), 'verbose_name': 'Atendimento Geral', 'verbose_name_plural': 'Atendimentos Gerais'},
        ),
    ]
