# Generated by Django 3.2 on 2023-01-24 15:24

from django.db import migrations

"""
Atualiza o atendimento das pastas cujo atendimento não seja "inicial"
para o inicial do respectivo atendimento (retorno)
"""
UPDATE_PASTAS_DOCUMENTO = """
UPDATE
	atendimento_pastadocumento att_pasta
SET
	atendimento_id = att_inicial.inicial_id
FROM (
	SELECT
		att.id,
		att.inicial_id
	FROM
		atendimento_atendimento att
	WHERE
		att.id IN (
			SELECT
				atendimento_id
			FROM
				atendimento_pastadocumento
		)
	AND att.inicial_id IS NOT NULL
) att_inicial
WHERE
	att_pasta.atendimento_id = att_inicial.id
"""



class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0127_grupo_defensorias_permissoes_agend'),
    ]

    operations = [
        migrations.RunSQL(UPDATE_PASTAS_DOCUMENTO)
    ]
