# Generated by Django 3.2 on 2023-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0128_update_pastas_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Pergunta obrigatória?'),
        ),
    ]
