# Generated by Django 3.2 on 2023-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0129_pergunta_obrigatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupodedefensoriasparaagendamento',
            name='aceitar_agend_extrapauta',
            field=models.BooleanField(default=False, help_text='Permitir que as defensorias do grupo e o disk 129 agendem extra-pauta', verbose_name='Aceitar agendamento extra-pauta'),
        ),
    ]
