# Generated by Django 3.2 on 2023-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0130_alter_grupodedefensoriasparaagendamento_aceitar_agend_extrapauta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['origem', 'tipo'], name='atendimento_atend_idx_001'),
        ),
        migrations.AddIndex(
            model_name='atendimentovisualizacao',
            index=models.Index(fields=['atendimento', 'visualizado_por'], name='atendimento_atend_vis_idx_001'),
        ),
        migrations.AddIndex(
            model_name='cronometro',
            index=models.Index(condition=models.Q(finalizado=False), fields=['atendimento', 'servidor'], name='atendimento_cronometro_idx_001'),
        ),
        migrations.AddIndex(
            model_name='cronometro',
            index=models.Index(fields=['atendimento', 'termino'], name='atendimento_cronometro_idx_002'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['atendimento', 'documento_online'], name='atendimento_documento_idx_001'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['atendimento', 'pessoa', 'tipo'], name='atendimento_pessoa_idx_001'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['atendimento', 'responsavel', 'data_final'], name='atendimento_tarefa_idx_001'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(condition=models.Q(origem=None), fields=['data_finalizado'], name='atendimento_tarefa_idx_002'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(condition=models.Q(('data_finalizado', None), ('origem', None)), fields=['data_final', 'status'], name='atendimento_tarefa_idx_003'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(condition=models.Q(('data_finalizado', None), ('origem', None)), fields=['status'], name='atendimento_tarefa_idx_004'),
        ),
        migrations.AddIndex(
            model_name='tarefavisualizacao',
            index=models.Index(fields=['tarefa', 'visualizada_por'], name='atendimento_tarefa_vis_idx_001'),
        ),
    ]
