# Generated by Django 3.2 on 2022-04-19 14:27

import cuser.fields
from django.conf import settings
from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion

LISTA_ESTABELECIMENTOS_PENAIS = (
    (0, 'Delegacia'),
    (1, 'Presídio/Penitenciária'),
    (2, 'Cadeia pública / Casa de detenção ou similares'),
    (3, 'Casa do albergado'),
    (4, 'Colônia agrícola, industrial ou similar'),
    (5, 'Hospital de Custódia e Tratamento Psiquiátrico'),
    (6, 'Hospital Particular'),
    (7, 'Hospital Público'),
)

def carregar_dados(apps, schema_editor):

    Estabelecimento = apps.get_model('nadep', 'EstabelecimentoPenal')
    TipoEstabelecimento = apps.get_model('nadep', 'TipoEstabelecimentoPenal')

    for id, nome in LISTA_ESTABELECIMENTOS_PENAIS:
        TipoEstabelecimento.objects.create(id=id, nome=nome)

def reverse_carregar_dados(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadep', '0046_django_32'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentopenal',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimentopenal',
            name='destinado_ao_sexo',
            field=models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Ambos')], default=0, verbose_name='Destinado ao sexo',),
        ),
        migrations.AddField(
            model_name='estabelecimentopenal',
            name='inspecionado_pela_dpe',
            field=models.BooleanField(default=True, verbose_name='Inspecionado pela DPE?'),
        ),
        migrations.CreateModel(
            name='TipoEstabelecimentoPenal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=256)),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nadep_tipoestabelecimentopenal_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nadep_tipoestabelecimentopenal_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nadep_tipoestabelecimentopenal_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Estabelecimento Penal',
                'verbose_name_plural': 'Tipos de Estabelecimento Penal',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(
            code=carregar_dados,
            reverse_code=reverse_carregar_dados,
        ),
        migrations.AlterField(
            model_name='estabelecimentopenal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nadep.tipoestabelecimentopenal'),
        ),
    ]
