# Generated by Django 3.2 on 2022-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comarca', '0006_guiche_defensoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiche',
            name='andar',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Qual andar?'),
        ),
        migrations.AddField(
            model_name='guiche',
            name='tipo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Guichê'), (2, 'Sala')], default=1, null=True, verbose_name='Tipo de guichê'),
        ),
        migrations.AddField(
            model_name='predio',
            name='qtd_andares',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Deixar zero caso tenha somente o térreo', null=True, verbose_name='Quantidade de andares'),
        ),
    ]
