# Generated by Django 3.2 on 2021-10-19 11:00
# Importações necessárias

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Classe de migração do Django, usado para criar o modeloso "HistoricoConsultaAvisos" no banco de dados.

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procapi_client', '0010_respostaamigavel_respostatecnica'),
    ]
# altera as opções do modelo "HistoricoConsultaDocumento'
    operations = [
        migrations.AlterModelOptions(
            name='historicoconsultadocumento',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Histórico Consulta de Documentos (log de acesso de usuários)', 'verbose_name_plural': 'Históricos Consulta de Documentos (log de acesso de usuários)'},
        ),
        migrations.CreateModel(
            name='HistoricoConsultaAvisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('data_consulta', models.DateTimeField(null=True, verbose_name='Data da Consulta')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_historicoconsultaavisos_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_historicoconsultaavisos_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_historicoconsultaavisos_modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Consulta de Avisos pendentes (task de cadastro automático de processos)',
                'verbose_name_plural': 'Históricos Consulta de Avisos pendentes (task de cadastro automático de processos)',
                'ordering': ['-cadastrado_em'],
            },
        ),
    ]
