# Generated by Django 3.2 on 2022-05-25 14:15
# Importações necessárias

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Classe de migração do Django, usado para criar o modeloso "OrgaoJulgador" no banco de dados.

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0066_defensoriavara_regex'),
        ('procapi_client', '0011_historico_consulta_avisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoJulgador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=512, verbose_name='Nome')),
                ('codigo_mni', models.PositiveSmallIntegerField(verbose_name='Código MNI')),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_orgaojulgador_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_orgaojulgador_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procapi_client_orgaojulgador_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('sistema_webservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procapi_client.sistemawebservice', verbose_name='Sistema Web Service')),
                ('vara', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contrib.vara', verbose_name='Vara')),
            ],
            options={
                'verbose_name': 'Órgão Julgador ProcAPI',
                'verbose_name_plural': 'Órgãos Julgadores ProcAPI',
                'ordering': ['vara__comarca', 'vara__nome', 'sistema_webservice__nome', 'nome'],
                'unique_together': {('codigo_mni', 'sistema_webservice')},
            },
        ),
    ]
