# Generated by Django 3.2 on 2022-11-04 10:58
# Importações necessárias
from django.db import migrations, models

# Classe responsável pela migração de banco de dados, que envolvem a alteração de opções de modelo e a adição de novos campos aos modelos existentes.
class Migration(migrations.Migration):

    dependencies = [
        ('procapi_client', '0015_tipoarquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoconsultaavisos',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Histórico Consulta Lista de Avisos Pendentes', 'verbose_name_plural': 'Históricos Consulta Lista de Avisos Pendentes'},
        ),
        migrations.AlterModelOptions(
            name='historicoconsultadocumento',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Histórico Consulta de Documento', 'verbose_name_plural': 'Históricos Consulta de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='historicoconsultaprocesso',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Histórico Consulta de Processo', 'verbose_name_plural': 'Históricos Consulta de Processos'},
        ),
        migrations.AlterModelOptions(
            name='historicoconsultaprocessos',
            options={'ordering': ['-data_final'], 'verbose_name': 'Histórico Consulta Lista de Processos', 'verbose_name_plural': 'Históricos Consulta Lista de Processos'},
        ),
        migrations.AlterModelOptions(
            name='historicoconsultateorcomunicacao',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Histórico Consulta de Teor Comunicação', 'verbose_name_plural': 'Históricos Consulta de Teor Comunicação'},
        ),
        migrations.AddField(
            model_name='historicoconsultadocumento',
            name='grau',
            field=models.SmallIntegerField(choices=[(1, '1º Grau'), (2, '2º Grau'), (3, 'STF/STJ')], default=0),
        ),
        migrations.AddField(
            model_name='historicoconsultadocumento',
            name='sucesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicoconsultaprocesso',
            name='grau',
            field=models.SmallIntegerField(choices=[(1, '1º Grau'), (2, '2º Grau'), (3, 'STF/STJ')], default=0),
        ),
        migrations.AddField(
            model_name='historicoconsultaprocesso',
            name='sucesso',
            field=models.BooleanField(default=True),
        ),
    ]
