# Generated by Django 3.2 on 2021-05-24 16:19

import contrib.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0053_defesoria_cabecalho_rodape_ged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='enderecohistorico',
            name='principal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='papel',
            field=models.ForeignKey(help_text='Conjunto de Permisssões do usuário', limit_choices_to=contrib.models.limitar_choices_papel, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='contrib.papel'),
        ),
    ]
