# Generated by Django 3.2 on 2021-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0055_defensoria_mae_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='exibir_em_documento_assistido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='exibir_em_documento_atendimento',
            field=models.BooleanField(default=False),
        ),
    ]
