# Generated by Django 3.2 on 2021-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0056_documento_exibir_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoria',
            name='agendamento_online',
            field=models.BooleanField(default=False, verbose_name='Possui agendamento online?'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='eh_mutirao',
            field=models.BooleanField(default=False, verbose_name='Unidade do Mutirão?'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='modalidade',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Presencial'), (2, 'Remoto')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Telefone da Unidade'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='triagem',
            field=models.BooleanField(default=False, verbose_name='Possui triagem?'),
        ),
    ]
