# Generated by Django 3.2 on 2021-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0058_cartorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoriavara',
            name='parte',
            field=models.SmallIntegerField(choices=[(0, 'Ativa (autora)'), (1, 'Passiva (ré)'), (2, 'Terceira'), (3, 'Vítima'), (4, 'Assistente simples desinteressado (amicus curiae e vulnerabilis)')], default=0),
        ),
    ]
