# Generated by Django 3.2 on 2021-10-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0059_defensoriavara_parte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensoriavara',
            name='parte',
        ),
    ]
