# Generated by Django 3.2 on 2021-11-17 10:19

from django.db import migrations, models


def migrate_data(apps, schema_editor):

    AGENDAMENTO_NINGUEM = 0
    Defensoria = apps.get_model("contrib", "Defensoria")

    for defensoria in Defensoria.objects.filter(aceita_agendamento_pauta=False):
        defensoria.novo_aceita_agendamento_pauta = AGENDAMENTO_NINGUEM
        defensoria.save()

    for defensoria in Defensoria.objects.filter(aceita_agendamento_extra=False):
        defensoria.novo_aceita_agendamento_extra = AGENDAMENTO_NINGUEM
        defensoria.save()

    for defensoria in Defensoria.objects.filter(aceita_encaminhamento_pauta=False):
        defensoria.novo_aceita_encaminhamento_pauta = AGENDAMENTO_NINGUEM
        defensoria.save()

    for defensoria in Defensoria.objects.filter(aceita_encaminhamento_extra=False):
        defensoria.novo_aceita_encaminhamento_extra = AGENDAMENTO_NINGUEM
        defensoria.save()


def reverse_migrate_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0060_remove_defensoriavara_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoria',
            name='novo_aceita_agendamento_extra',
            field=models.SmallIntegerField(choices=[(0, 'Ninguém'), (1, 'Todos'), (2, 'Apenas Setor de Agendamento (perm: view_129, view_recepcao)'), (3, 'Apenas Gabinete de Defensor (perm: view_defensor)')], default=1, verbose_name='Quem pode agendar na extra-pauta?'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='novo_aceita_agendamento_pauta',
            field=models.SmallIntegerField(choices=[(0, 'Ninguém'), (1, 'Todos'), (2, 'Apenas Setor de Agendamento (perm: view_129, view_recepcao)'), (3, 'Apenas Gabinete de Defensor (perm: view_defensor)')], default=1, verbose_name='Quem pode agendar na pauta?'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='novo_aceita_encaminhamento_extra',
            field=models.SmallIntegerField(choices=[(0, 'Ninguém'), (1, 'Todos'), (2, 'Apenas Setor de Agendamento (perm: view_129, view_recepcao)'), (3, 'Apenas Gabinete de Defensor (perm: view_defensor)')], default=1, verbose_name='Quem pode encaminhar na extra-pauta?'),
        ),
        migrations.AddField(
            model_name='defensoria',
            name='novo_aceita_encaminhamento_pauta',
            field=models.SmallIntegerField(choices=[(0, 'Ninguém'), (1, 'Todos'), (2, 'Apenas Setor de Agendamento (perm: view_129, view_recepcao)'), (3, 'Apenas Gabinete de Defensor (perm: view_defensor)')], default=1, verbose_name='Quem pode encaminhar na pauta?'),
        ),
        migrations.RunPython(
            code=migrate_data,
            reverse_code=reverse_migrate_data,
        )
    ]
