# Generated by Django 3.2 on 2021-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0061_defensoria_aceita_agendamento_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensoria',
            name='aceita_agendamento_extra',
        ),
        migrations.RemoveField(
            model_name='defensoria',
            name='aceita_agendamento_pauta',
        ),
        migrations.RemoveField(
            model_name='defensoria',
            name='aceita_encaminhamento_extra',
        ),
        migrations.RemoveField(
            model_name='defensoria',
            name='aceita_encaminhamento_pauta',
        ),
        migrations.RenameField(
            model_name='defensoria',
            old_name='novo_aceita_agendamento_extra',
            new_name='aceita_agendamento_extra',
        ),
        migrations.RenameField(
            model_name='defensoria',
            old_name='novo_aceita_agendamento_pauta',
            new_name='aceita_agendamento_pauta',
        ),
        migrations.RenameField(
            model_name='defensoria',
            old_name='novo_aceita_encaminhamento_extra',
            new_name='aceita_encaminhamento_extra',
        ),
        migrations.RenameField(
            model_name='defensoria',
            old_name='novo_aceita_encaminhamento_pauta',
            new_name='aceita_encaminhamento_pauta',
        ),
    ]
