# Generated by Django 3.2 on 2022-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0063_bairro_cep_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vara',
            name='grau',
            field=models.SmallIntegerField(choices=[(1, '1º Grau'), (2, '2º Grau'), (3, 'STF/STJ')], default=1),
        ),
    ]
