# Generated by Django 3.2 on 2022-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0064_vara_grau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papel',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Papel', 'verbose_name_plural': 'Papéis'},
        ),
        migrations.AlterField(
            model_name='papel',
            name='css_label_class',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('label-success', 'Success'), ('label-warning', 'Warning'), ('label-important', 'Important'), ('label-info', 'Info'), ('label-inverse', 'Inverse')], default='', help_text='Usado para definir a cor de labels', max_length=25, verbose_name='CSS Label Class'),
        ),
    ]
