# Generated by Django 3.2 on 2022-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0065_alter_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoriavara',
            name='regex',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Expressão regular da regra de distribuição (regex)'),
        ),
    ]
