# Generated by Django 3.2 on 2022-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0068_historicologin'),
    ]

    operations = [
        migrations.AddField(
            model_name='papel',
            name='marcar_usuario_como_defensor',
            field=models.BooleanField(default=False, help_text='Marcar usuário como defensor?'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='requer_matricula',
            field=models.BooleanField(default=True, help_text='Exige informar a matrícula no cadastro do servidor?'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='requer_superusuario',
            field=models.BooleanField(default=False, help_text='Disponível apenas para superusuários?'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='requer_supervisor',
            field=models.BooleanField(default=False, help_text='Exige informar um supervisor no cadastro do servidor?'),
        ),
    ]
