# Generated by Django 3.2 on 2022-09-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0069_papel_marcar_usuario_como_defensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defensoria',
            options={'ordering': ['comarca__nome', 'nome', 'numero'], 'permissions': (('view_all_defensorias', 'Pode ver todas defensorias'),), 'verbose_name': 'Defensoria', 'verbose_name_plural': 'Defensorias'},
        ),
    ]
