# Generated by Django 3.2 on 2022-10-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0071_cep_eh_geral_complemento_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuextra',
            name='local',
            field=models.CharField(choices=[('root', 'Root'), ('ajuda', 'Ajuda'), ('convenios', 'Convênios')], default='ajuda', max_length=255),
        ),
    ]
