# Generated by Django 3.2 on 2022-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0072_alter_menuextra_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoriavara',
            name='usuario_webservice',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do usuário webservice'),
        ),
    ]
