# Generated by Django 3.2 on 2023-01-09 14:33

import cuser.fields
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion

def migrate_data(apps, schema_editor):

    Etiqueta = apps.get_model("contrib", "Etiqueta")
    DefensoriaEtiqueta = apps.get_model("contrib", "DefensoriaEtiqueta")

    etiquetas = Etiqueta.objects.all().order_by('nome', 'id')
    etiquetas_nomes = []

    for etiqueta in etiquetas:

        # Obtém primeira etiqueta cadastrada com o mesmo nome
        etiqueta_principal = etiquetas.filter(nome=etiqueta.nome).first()

        # Adiciona vínculo etiqueta/defensoria
        DefensoriaEtiqueta.objects.update_or_create(
            etiqueta=etiqueta_principal,
            defensoria=etiqueta.defensoria,
            defaults={
                'cadastrado_por': etiqueta.cadastrado_por,
                'modificado_por': etiqueta.modificado_por,
                'desativado_por': etiqueta.desativado_por,
                'desativado_em': etiqueta.desativado_em,
            }
        )

        # Reativa etiqueta principal caso exista outra ativa
        if not etiqueta.desativado_em and etiqueta_principal.desativado_em:
            etiqueta_principal.desativado_em = None
            etiqueta_principal.desativado_por = None
            etiqueta_principal.save()

        # Se existe etiqueta com mesmo nome, renomeia
        if etiqueta.nome.lower() in etiquetas_nomes:
            etiqueta.nome = f'{etiqueta.nome} [id: {etiqueta.id} > {etiqueta_principal.id}]'
            etiqueta.desativado_em = timezone.now()
            etiqueta.save()

        etiquetas_nomes.append(etiqueta.nome.lower())


def reverse_migrate_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0074_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='defensoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etiquetas', to='contrib.defensoria'),
        ),
        migrations.CreateModel(
            name='DefensoriaEtiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado_em', models.DateTimeField(auto_now=True, null=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('cadastrado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrib_defensoriaetiqueta_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('defensoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.defensoria')),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrib_defensoriaetiqueta_desativado_por', to=settings.AUTH_USER_MODEL)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrib.etiqueta')),
                ('modificado_por', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrib_defensoriaetiqueta_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('usuarios_autorizados', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contrib_defensoria_etiquetas',
                'ordering': ['defensoria', 'etiqueta'],
            },
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='defensorias',
            field=models.ManyToManyField(through='contrib.DefensoriaEtiqueta', to='contrib.Defensoria'),
        ),
        migrations.RunPython(
            code=migrate_data,
            reverse_code=reverse_migrate_data,
        ),
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='defensoria',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
