# Generated by Django 3.2 on 2023-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0075_defensoria_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
