# Generated by Django 3.2 on 2023-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0076_alter_etiqueta_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensoria',
            name='grau',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1º Grau'), (2, '2º Grau')], db_index=True, default=1, null=True),
        ),
    ]
