# Generated by Django 3.2 on 2023-05-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meritocracia', '0001_initial'),
        ('contrib', '0078_defensoria_nivel_sigilo_indeferimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensoria',
            name='indicador_meritocracia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meritocracia.indicadormeritocracia'),
        ),
    ]
