# Generated by Django 2.1.4 on 2021-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
            ],
        ),
    ]
