# Generated by Django 2.1.4 on 2022-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('calc_jur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=6)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
            ],
        ),
    ]
