# Generated by Django 2.1.4 on 2022-01-19 20:32

from django.db import migrations

salarios = {
    "2000": 151.0,
    "2001": 180.0,
    "2002": 200.0,
    "2003": 240.0,
    "2004": 260.0,
    "2005": 300.0,
    "2006": 350.0,
    "2007": 380.0,
    "2008": 415.0,
    "2009": 465.0,
    "2010": 510.0,
    "2011": 545.0,
    "2012": 622.0,
    "2013": 678.0,
    "2014": 724.0,
    "2015": 788.0,
    "2016": 880.0,
    "2017": 937.0,
    "2018": 954.0,
    "2019": 998.0,
    "2020": 1045.0,
    "2021": 1100.0,
    "2022": 1212.0,
    "2023": 1320.0,
}


# forwards
def insert_data(apps, schema_editor):
    salario_model = apps.get_model('calc_jur', 'Salario')
    for k, v in salarios.items():
        salario = salario_model(ano=k, valor=v)
        salario.save()


# backwards
def drop_data(apps, schema_editor):
    salario_model = apps.get_model('calc_jur', 'Salario')
    for k, v in salarios.items():
        salario_model.objects.filter(ano=k).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('calc_jur', '0002_inpc'),
    ]

    operations = [
        migrations.RunPython(insert_data, drop_data),
    ]
