# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0016_atuacao_habilitado_visualiza_chat_edefensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensor',
            name='nao_possui_eproc',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
