# Generated by Django 3.2 on 2021-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0018_alter_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atuacao',
            name='designacao_extraordinaria',
            field=models.BooleanField(default=False, verbose_name='É designação extraordinária?'),
        ),
        migrations.AddField(
            model_name='atuacao',
            name='observacao',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Observação'),
        ),
    ]
