# Generated by Django 3.2 on 2022-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0019_atuacao_designacao_extraordinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='data_expiracao_credenciais_mni',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de expiração das credenciais do MNI'),
        ),
    ]
