# Generated by Django 3.2 on 2022-07-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0021_remover_campos_depreciados'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditalConcorrenciaPlantao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de início do período do Plantão')),
                ('data_final', models.DateField(verbose_name='Data o final do período do Plantão')),
                ('data_abertura_inscricao', models.DateField(verbose_name='Data de abertura de inscrições ao Plantão')),
                ('data_fechamento_inscricao', models.DateField(verbose_name='Data de fechamento de inscrições ao Plantão')),
                ('status', models.SmallIntegerField(choices=[(0, 'Ativo'), (1, 'Cancelado'), (2, 'Exaurido')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Edital de Concorrência à Plantão',
                'verbose_name_plural': 'Editais de Concorrência à Plantão',
                'permissions': (('view_inscricao_plantao', 'Pode se inscrever em edital de concorrência de plantão'),),
            },
        ),
        migrations.CreateModel(
            name='VagaEditalPlantao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início da vaga')),
                ('data_final', models.DateField(verbose_name='Data do final da vaga')),
            ],
            options={
                'verbose_name': 'Vaga para Edital de Plantão',
                'verbose_name_plural': 'Vagas para Edital de Plantão',
            },
        ),
        migrations.AddField(
            model_name='defensor',
            name='posicao_lista_antiguidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InscricaoEditalPlantao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('defensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defensor.defensor')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defensor.editalconcorrenciaplantao')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defensor.vagaeditalplantao')),
            ],
            options={
                'verbose_name': 'Inscrição a Edital de Plantão',
                'verbose_name_plural': 'Inscrições a Edital de Plantão',
            },
        ),
        migrations.AddField(
            model_name='editalconcorrenciaplantao',
            name='vagas',
            field=models.ManyToManyField(to='defensor.VagaEditalPlantao'),
        ),
    ]
