# Generated by Django 3.2 on 2022-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0022_add_edital_concorrencia_plantao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atuacao',
            name='foi_enviado_email_plantao',
            field=models.BooleanField(default=False, verbose_name='Foi enviado e-mail c/ extrato do plantão?'),
        ),
    ]
