# Generated by Django 3.2 on 2023-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0023_atuacao_foi_enviado_email_plantao'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atuacao',
            index=models.Index(fields=['defensor', 'data_inicial'], name='defensor_atuacao_idx_001'),
        ),
        migrations.AddIndex(
            model_name='atuacao',
            index=models.Index(fields=['defensoria', 'defensor', 'tipo', 'data_inicial'], name='defensor_atuacao_idx_002'),
        ),
    ]
