# Generated by Django 3.2 on 2023-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensor', '0024_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='data_envio_ultimo_email_distribuicao_processos',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de envio do último e-mail de distribuição de processos'),
        ),
    ]
