# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerante', '0004_auto_20180118_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_autorizacao',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Data de Autorização'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_exclusao',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateField(verbose_name='Data Término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicial',
            field=models.DateField(verbose_name='Data Início'),
        ),
    ]
