# Generated by Django 3.2 on 2023-06-06 20:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware

# Migração com o Django

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aceite', '0002_termo_tipo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceite_termo_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termo',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='aceite_termo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termoresposta',
            name='cadastrado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceite_termoresposta_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termoresposta',
            name='modificado_por',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, related_name='aceite_termoresposta_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
