insert into contrib_documento values(1,'Carteira de Identidade (RG)',True);
insert into contrib_documento values(2,'Cadastro de Pessoa Física (CPF)',True);
insert into contrib_documento values(3,'Comprovante de Endereço',True);
insert into contrib_documento values(4,'Comprovante de Renda',True);
insert into contrib_documento values(5,'Declaração de Nascido Vivo',True);
insert into contrib_documento values(6,'Certidão de Nascimento',True);
insert into contrib_documento values(7,'Certidão de Casamento',True);
insert into contrib_documento values(8,'Certidão de Óbito',True);
insert into contrib_documento values(9,'Certidão de União Estável',True);
insert into contrib_documento values(10,'Título de Eleitor',True);
insert into contrib_documento values(11,'Carteira Nacional de Habilitação (CNH)',True);
insert into contrib_documento values(12,'Carteira de Trabalho (CTPS)',True);
insert into contrib_documento values(13,'Cartão SUS',True);
insert into contrib_documento values(14,'Certificado de Alistamento Militar',True);
insert into contrib_documento values(15,'Atestado de Antecedentes Criminais',True);
insert into contrib_documento values(16,'Certidão de Igualdade de Direitos',True);
insert into contrib_documento values(17,'Certidão Negativa de Débitos',True);
insert into contrib_documento values(18,'Previdência Social (Cartão INSS)',True);
insert into contrib_documento values(19,'Novo Registro de Identidade Civil (RIC)',True);
insert into contrib_documento values(20,'Diploma',True);
insert into contrib_documento values(21,'Carteira de Estudante',True);
insert into contrib_documento values(22,'Registro Nacional de Estrangeiros',True);
insert into contrib_documento values(23,'Visto para Estrangeiros',True);
insert into contrib_documento values(24,'Passaporte',True);
insert into contrib_documento values(25,'Certificado de Naturalização',True);