insert into contrib_estado (id,nome,uf) values(11,'Rondônia','RO');
insert into contrib_estado (id,nome,uf) values(12,'Acre','AC');
insert into contrib_estado (id,nome,uf) values(13,'Amazonas','AM');
insert into contrib_estado (id,nome,uf) values(14,'Roraima','RR');
insert into contrib_estado (id,nome,uf) values(15,'Pará','PA');
insert into contrib_estado (id,nome,uf) values(16,'Amapá','AP');
insert into contrib_estado (id,nome,uf) values(17,'Tocantins','TO');
insert into contrib_estado (id,nome,uf) values(21,'Maranhão','MA');
insert into contrib_estado (id,nome,uf) values(22,'Piauí','PI');
insert into contrib_estado (id,nome,uf) values(23,'Ceará','CE');
insert into contrib_estado (id,nome,uf) values(24,'Rio Grande no Norte','RN');
insert into contrib_estado (id,nome,uf) values(25,'Paraíba','PB');
insert into contrib_estado (id,nome,uf) values(26,'Pernambuco','PE');
insert into contrib_estado (id,nome,uf) values(27,'Alagoas','AL');
insert into contrib_estado (id,nome,uf) values(28,'Sergipe','SE');
insert into contrib_estado (id,nome,uf) values(29,'Bahia','BA');
insert into contrib_estado (id,nome,uf) values(31,'Minas Gerais','MG');
insert into contrib_estado (id,nome,uf) values(32,'Espírito Santo','ES');
insert into contrib_estado (id,nome,uf) values(33,'Rio de Janeiro','RJ');
insert into contrib_estado (id,nome,uf) values(35,'São Paulo','SP');
insert into contrib_estado (id,nome,uf) values(41,'Paraná','PR');
insert into contrib_estado (id,nome,uf) values(42,'Santa Catarina','SC');
insert into contrib_estado (id,nome,uf) values(43,'Rio Grande do Sul','RS');
insert into contrib_estado (id,nome,uf) values(50,'Mato Grosso do Sul','MS');
insert into contrib_estado (id,nome,uf) values(51,'Mato Grosso','MT');
insert into contrib_estado (id,nome,uf) values(52,'Goiás','GO');
insert into contrib_estado (id,nome,uf) values(53,'Distrito Federal','DF');
