insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AF', 'AFG', '004', 'Afeganistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ZA', 'ZAF', '710', 'África do Sul', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AX', 'ALA', '248', 'Åland, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AL', 'ALB', '008', 'Albânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DE', 'DEU', '276', 'Alemanha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AD', 'AND', '020', 'Andorra', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AO', 'AGO', '024', 'Angola', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AI', 'AIA', '660', 'Anguilla', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AQ', 'ATA', '010', 'Antárctida', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AG', 'ATG', '028', 'Antigua e Barbuda', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AN', 'ANT', '530', 'Antilhas Holandesas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SA', 'SAU', '682', 'Arábia Saudita', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DZ', 'DZA', '012', 'Argélia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AR', 'ARG', '032', 'Argentina', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AM', 'ARM', '051', 'Arménia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AW', 'ABW', '533', 'Aruba', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AU', 'AUS', '036', 'Austrália', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AT', 'AUT', '040', 'Áustria', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AZ', 'AZE', '031', 'Azerbeijão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BS', 'BHS', '044', 'Bahamas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BH', 'BHR', '048', 'Bahrain', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BD', 'BGD', '050', 'Bangladesh', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BB', 'BRB', '052', 'Barbados', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BE', 'BEL', '056', 'Bélgica', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BZ', 'BLZ', '084', 'Belize', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BJ', 'BEN', '204', 'Benin', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BM', 'BMU', '060', 'Bermuda', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BY', 'BLR', '112', 'Bielo-Rússia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BO', 'BOL', '068', 'Bolívia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BA', 'BIH', '070', 'Bósnia-Herzegovina', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BW', 'BWA', '072', 'Botswana', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BV', 'BVT', '074', 'Bouvet, Ilha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BR', 'BRA', '076', 'Brasil', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BN', 'BRN', '096', 'Brunei', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BG', 'BGR', '100', 'Bulgária', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BF', 'BFA', '854', 'Burkina Faso', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BI', 'BDI', '108', 'Burundi', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('BT', 'BTN', '064', 'Butão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CV', 'CPV', '132', 'Cabo Verde', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KH', 'KHM', '116', 'Cambodja', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CM', 'CMR', '120', 'Camarões', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CA', 'CAN', '124', 'Canadá', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KY', 'CYM', '136', 'Cayman, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KZ', 'KAZ', '398', 'Cazaquistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CF', 'CAF', '140', 'Centro-africana, República', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TD', 'TCD', '148', 'Chade', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CZ', 'CZE', '203', 'Checa, República', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CL', 'CHL', '152', 'Chile', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CN', 'CHN', '156', 'China', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CY', 'CYP', '196', 'Chipre', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CX', 'CXR', '162', 'Christmas, Ilha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CC', 'CCK', '166', 'Cocos, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CO', 'COL', '170', 'Colômbia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KM', 'COM', '174', 'Comores', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CG', 'COG', '178', 'Congo, República do', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CD', 'COD', '180', 'Congo, República Democrática do (antigo Zaire)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CK', 'COK', '184', 'Cook, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KR', 'KOR', '410', 'Coreia do Sul', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KP', 'PRK', '408', 'Coreia, República Democrática da (Coreia do Norte)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CI', 'CIV', '384', 'Costa do Marfim', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CR', 'CRI', '188', 'Costa Rica', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HR', 'HRV', '191', 'Croácia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CU', 'CUB', '192', 'Cuba', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DK', 'DNK', '208', 'Dinamarca', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DJ', 'DJI', '262', 'Djibouti', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DM', 'DMA', '212', 'Dominica', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('DO', 'DOM', '214', 'Dominicana, República', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('EG', 'EGY', '818', 'Egipto', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SV', 'SLV', '222', 'El Salvador', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AE', 'ARE', '784', 'Emiratos Árabes Unidos', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('EC', 'ECU', '218', 'Equador', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ER', 'ERI', '232', 'Eritreia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SK', 'SVK', '703', 'Eslováquia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SI', 'SVN', '705', 'Eslovénia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ES', 'ESP', '724', 'Espanha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('US', 'USA', '840', 'Estados Unidos da América', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('EE', 'EST', '233', 'Estónia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ET', 'ETH', '231', 'Etiópia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FO', 'FRO', '234', 'Faroe, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FJ', 'FJI', '242', 'Fiji', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PH', 'PHL', '608', 'Filipinas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FI', 'FIN', '246', 'Finlândia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FR', 'FRA', '250', 'França', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GA', 'GAB', '266', 'Gabão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GM', 'GMB', '270', 'Gâmbia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GH', 'GHA', '288', 'Gana', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GE', 'GEO', '268', 'Geórgia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GS', 'SGS', '239', 'Geórgia do Sul e Sandwich do Sul, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GI', 'GIB', '292', 'Gibraltar', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GR', 'GRC', '300', 'Grécia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GD', 'GRD', '308', 'Grenada', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GL', 'GRL', '304', 'Gronelândia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GP', 'GLP', '312', 'Guadeloupe', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GU', 'GUM', '316', 'Guam', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GT', 'GTM', '320', 'Guatemala', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GG', 'GGY', '831', 'Guernsey', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GY', 'GUY', '328', 'Guiana', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GF', 'GUF', '254', 'Guiana Francesa', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GW', 'GNB', '624', 'Guiné-Bissau', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GN', 'GIN', '324', 'Guiné-Conacri', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GQ', 'GNQ', '226', 'Guiné Equatorial', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HT', 'HTI', '332', 'Haiti', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HM', 'HMD', '334', 'Heard e Ilhas McDonald, Ilha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HN', 'HND', '340', 'Honduras', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HK', 'HKG', '344', 'Hong Kong', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('HU', 'HUN', '348', 'Hungria', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('YE', 'YEM', '887', 'Iémen', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IN', 'IND', '356', 'Índia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ID', 'IDN', '360', 'Indonésia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IQ', 'IRQ', '368', 'Iraque', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IR', 'IRN', '364', 'Irão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IE', 'IRL', '372', 'Irlanda', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IS', 'ISL', '352', 'Islândia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IL', 'ISR', '376', 'Israel', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IT', 'ITA', '380', 'Itália', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('JM', 'JAM', '388', 'Jamaica', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('JP', 'JPN', '392', 'Japão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('JE', 'JEY', '832', 'Jersey', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('JO', 'JOR', '400', 'Jordânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KI', 'KIR', '296', 'Kiribati', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KW', 'KWT', '414', 'Kuwait', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LA', 'LAO', '418', 'Laos', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LS', 'LSO', '426', 'Lesoto', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LV', 'LVA', '428', 'Letónia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LB', 'LBN', '422', 'Líbano', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LR', 'LBR', '430', 'Libéria', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LY', 'LBY', '434', 'Líbia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LI', 'LIE', '438', 'Liechtenstein', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LT', 'LTU', '440', 'Lituânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LU', 'LUX', '442', 'Luxemburgo', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MO', 'MAC', '446', 'Macau', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MK', 'MKD', '807', 'Macedónia, República da', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MG', 'MDG', '450', 'Madagáscar', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MY', 'MYS', '458', 'Malásia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MW', 'MWI', '454', 'Malawi', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MV', 'MDV', '462', 'Maldivas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ML', 'MLI', '466', 'Mali', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MT', 'MLT', '470', 'Malta', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FK', 'FLK', '238', 'Malvinas, Ilhas (Falkland)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IM', 'IMN', '833', 'Man, Ilha de', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MP', 'MNP', '580', 'Marianas Setentrionais', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MA', 'MAR', '504', 'Marrocos', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MH', 'MHL', '584', 'Marshall, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MQ', 'MTQ', '474', 'Martinica', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MU', 'MUS', '480', 'Maurícia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MR', 'MRT', '478', 'Mauritânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('YT', 'MYT', '175', 'Mayotte', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('UM', 'UMI', '581', 'Menores Distantes dos Estados Unidos, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MX', 'MEX', '484', 'México', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MM', 'MMR', '104', 'Myanmar (antiga Birmânia)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('FM', 'FSM', '583', 'Micronésia, Estados Federados da', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MZ', 'MOZ', '508', 'Moçambique', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MD', 'MDA', '498', 'Moldávia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MC', 'MCO', '492', 'Mónaco', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MN', 'MNG', '496', 'Mongólia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ME', 'MNE', '499', 'Montenegro', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('MS', 'MSR', '500', 'Montserrat', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NA', 'NAM', '516', 'Namíbia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NR', 'NRU', '520', 'Nauru', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NP', 'NPL', '524', 'Nepal', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NI', 'NIC', '558', 'Nicarágua', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NE', 'NER', '562', 'Níger', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NG', 'NGA', '566', 'Nigéria', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NU', 'NIU', '570', 'Niue', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NF', 'NFK', '574', 'Norfolk, Ilha', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NO', 'NOR', '578', 'Noruega', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NC', 'NCL', '540', 'Nova Caledónia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NZ', 'NZL', '554', 'Nova Zelândia (Aotearoa)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('OM', 'OMN', '512', 'Oman', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('NL', 'NLD', '528', 'Países Baixos (Holanda)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PW', 'PLW', '585', 'Palau', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PS', 'PSE', '275', 'Palestina', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PA', 'PAN', '591', 'Panamá', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PG', 'PNG', '598', 'Papua-Nova Guiné', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PK', 'PAK', '586', 'Paquistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PY', 'PRY', '600', 'Paraguai', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PE', 'PER', '604', 'Peru', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PN', 'PCN', '612', 'Pitcairn', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PF', 'PYF', '258', 'Polinésia Francesa', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PL', 'POL', '616', 'Polónia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PR', 'PRI', '630', 'Porto Rico', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PT', 'PRT', '620', 'Portugal', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('QA', 'QAT', '634', 'Qatar', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KE', 'KEN', '404', 'Quénia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KG', 'KGZ', '417', 'Quirguistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('GB', 'GBR', '826', 'Reino Unido da Grã-Bretanha e Irlanda do Norte', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('RE', 'REU', '638', 'Reunião', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('RO', 'ROU', '642', 'Roménia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('RW', 'RWA', '646', 'Ruanda', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('RU', 'RUS', '643', 'Rússia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('EH', 'ESH', '732', 'Saara Ocidental', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('AS', 'ASM', '016', 'Samoa Americana', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('WS', 'WSM', '882', 'Samoa (Samoa Ocidental)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('PM', 'SPM', '666', 'Saint Pierre et Miquelon', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SB', 'SLB', '090', 'Salomão, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('KN', 'KNA', '659', 'São Cristóvão e Névis (Saint Kitts e Nevis)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SM', 'SMR', '674', 'San Marino', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ST', 'STP', '678', 'São Tomé e Príncipe', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VC', 'VCT', '670', 'São Vicente e Granadinas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SH', 'SHN', '654', 'Santa Helena', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LC', 'LCA', '662', 'Santa Lúcia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SN', 'SEN', '686', 'Senegal', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SL', 'SLE', '694', 'Serra Leoa', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('RS', 'SRB', '688', 'Sérvia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SC', 'SYC', '690', 'Seychelles', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SG', 'SGP', '702', 'Singapura', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SY', 'SYR', '760', 'Síria', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SO', 'SOM', '706', 'Somália', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('LK', 'LKA', '144', 'Sri Lanka', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SZ', 'SWZ', '748', 'Suazilândia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SD', 'SDN', '736', 'Sudão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SE', 'SWE', '752', 'Suécia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('CH', 'CHE', '756', 'Suíça', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SR', 'SUR', '740', 'Suriname', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('SJ', 'SJM', '744', 'Svalbard e Jan Mayen', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TH', 'THA', '764', 'Tailândia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TW', 'TWN', '158', 'Taiwan', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TJ', 'TJK', '762', 'Tajiquistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TZ', 'TZA', '834', 'Tanzânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TF', 'ATF', '260', 'Terras Austrais e Antárticas Francesas (TAAF)', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('IO', 'IOT', '086', 'Território Britânico do Oceano Índico', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TL', 'TLS', '626', 'Timor-Leste', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TG', 'TGO', '768', 'Togo', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TK', 'TKL', '772', 'Toquelau', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TO', 'TON', '776', 'Tonga', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TT', 'TTO', '780', 'Trindade e Tobago', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TN', 'TUN', '788', 'Tunísia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TC', 'TCA', '796', 'Turks e Caicos', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TM', 'TKM', '795', 'Turquemenistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TR', 'TUR', '792', 'Turquia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('TV', 'TUV', '798', 'Tuvalu', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('UA', 'UKR', '804', 'Ucrânia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('UG', 'UGA', '800', 'Uganda', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('UY', 'URY', '858', 'Uruguai', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('UZ', 'UZB', '860', 'Usbequistão', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VU', 'VUT', '548', 'Vanuatu', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VA', 'VAT', '336', 'Vaticano', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VE', 'VEN', '862', 'Venezuela', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VN', 'VNM', '704', 'Vietname', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VI', 'VIR', '850', 'Virgens Americanas, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('VG', 'VGB', '092', 'Virgens Britânicas, Ilhas', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('WF', 'WLF', '876', 'Wallis e Futuna', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ZM', 'ZMB', '894', 'Zâmbia', true);
insert into contrib_pais (iso, iso3, numero, nome, ativo) values ('ZW', 'ZWE', '716', 'Zimbabwe', true);