# Generated by Django 3.2 on 2023-02-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0076_alter_etiqueta_nome'),
        ('propac', '0003_movimento_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.area'),
        ),
    ]
