# Generated by Django 3.2 on 2021-05-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_evento_categoria_de_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='evento_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.evento'),
        ),
    ]
