# Generated by Django 3.2 on 2022-10-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0012_categoria_auditoria_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eh_categoria_crc',
            field=models.BooleanField(default=False, verbose_name='É uma categoria que será utilizada no módulo CRC?'),
        ),
    ]
